language: python
cache: pip
python:
  - "3.6"
  - "3.8"
dist: bionic
os: linux

install: pip install -Ur requirements-test.txt

script: >-
  python -m pytest
  --durations=10
  --cov-report=term
  --cov=mnamer

after_success:
  - codecov
